server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1

zuul:
  prefix: /api #添加路由前缀
  retryable: true
  routes:
    item-service: /item/**  #商品微服务，将item路径指向item-service服务
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断超时时间5秒
ribbon:
  ConnectTimeout: 1000 #ribbon链接超时时长
  ReadTimeout: 3500 #ribbon读取超时时长
  MaxAutoRetries: 0 #当前服务器重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数